# Generated by Django 5.0.7 on 2024-08-02 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CheckUrl', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='UrlModel',
        ),
    ]
