# Generated by Django 5.0.7 on 2024-08-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckUrl', '0002_rename_url_urlmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='IPa',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='Region',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='Results',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='urlmodel',
            name='SubD',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
