# Generated by Django 5.0.7 on 2024-08-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckUrl', '0003_alter_urlmodel_ipa_alter_urlmodel_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='Url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
