# Generated by Django 5.0.7 on 2024-08-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckUrl', '0005_alter_urlmodel_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmodel',
            name='Url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
